import "./globals.css";
import {Jersey_15, Jersey_20, Jersey_25, Inter} from "next/font/google";
import Footer from "@/components/footer";
import Header from "@/components/header";

export const metadata = {
  title: "Yuta",
  description: "Generated by create next app",
}

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

const jersey15 = Jersey_15({
  subsets: ["latin"],
  variable: "--font-jersey15",
  weight: "400"
});

const jersey20 = Jersey_20({
  subsets: ["latin"],
  variable: "--font-jersey20",
  weight: "400"
});

const jersey25 = Jersey_25({
  subsets: ["latin"],
  variable: "--font-jersey25",
  weight: "400"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jersey15.variable} ${jersey20.variable} ${jersey25.variable} ${inter.variable}`}>
      <body
        className={`antialiased bg-background`}
      >
        <div id="smooth-wrapper">
          <div id="smooth-content">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
